### ISSUE TITLE
Create partial FTP mirror of Metabolights

### ISSUE THREAD

**Issue by sneumann** [sneumann/SemanticMetabolomics#1]
Create a mirror of the publicly available ISAtab files from  
ftp://ftp.ebi.ac.uk/pub/databases/metabolights/studies/public/

To avoid downloading Terabytes of data, just download
```
[isa]_*.txt and [am]_*.tsv and [am]_*.csv 
```
Check https://ohse.de/uwe/ftpcopy.html to create the mirror 
http://manpages.ubuntu.com/manpages/trusty/man1/ftpcopy.1.html 
because that can then be used as cron job.

**Comment by culpinnis** [comment]
I think @chweber has done this? At least we have some metabolites files lying around.
@chweber please give a comment and close this issue afterwards (if all necessary steps has been made). Also we need to know how the download was made. Please mail some kind of documentation to me. 
Cheers

**Comment by sneumann** [comment]
Metadata mirror can be created with lftp as shown above, 
and a copy is living in sneumann@balzer:/vol/metabolights/studies/public

**Comment by sneumann** [comment]
Just for reference: You can also use 
`rsync -rlpt -v -z --delete -f'+ [iasm]_*.[tc][xs][tv]' -f'+ */' -f'- *' rsync.ebi.ac.uk::pub/databases/metabolights/studies/public/ ./metabolights`

**Comment by culpinnis** [comment]
Did not mind that rsync can also handle ftp connections.  Great! I will integrate this into the update script.

**Comment by sneumann** [comment]
It can't, but rsync.ebi.ac.uk is an rsync server 
of the FTP server content.,,

**Comment by culpinnis** [comment]
Ah, okay.
Well, it solves the problem!
